config/routes.rb
BootstrapIt::Application.routes.draw do
  resources :posts do
    resources :comments
  end
  get 'message' => 'messages#new'
  get 'about_me' => 'welcome#about_me'
  root "welcome#index"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy

  validates :title,
            presence: true,
            length: { minimum: 5 }

  def self.seed_data!
    Post.delete_all
    25.times do
      Post.create(
        :title => Faker::Lorem.sentence(rand(2..10)).chomp('.'),
        :text  => Faker::Lorem.paragraphs(rand(2..8)).join('\n')
      )
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    @message = Message.new
  end

  def create
    @message = Message.new(params[:message])
    if @message.valid?
      # TODO send message here
      redirect_to root_url, notice: "Message sent! Thank you for contacting us."
    else
      render "new"
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to action: :show, id: @post.id
    else
      render 'edit'
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to action: :show, id: @post.id
    else
      render 'new'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to action: :index
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about_me

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.post, comment],
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br />
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/_nav_bar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="navbar-header">
    <%= link_to "Steve's Portfolio Page", root_path, class: "navbar-brand" %>
  </div>
  <ul class="nav navbar-nav">
    <li><%= link_to "My Blog", controller: "posts" %></li>
    <li><%= link_to "Contact Me", message_path %></li>
    <li><%= link_to "About Me", about_me_path %></li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BootstrapIt</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
<%= render partial: "layouts/nav_bar" %>
<%= yield %>

</div>
</body>
</html>

app/views/messages/new.html.erb
<h1>Contact Us</h1>


<%= form_for @message, url: message_path do |f| %>
<p>
  <%= f.label :name %><br>
  <%= f.text_field :name %>
</p>

<p>
  <%= f.label :email %><br>
  <%= f.text_field :email %>
</p>

<p>
  <%= f.label :message %><br>
  <%= f.text_area :message %>
</p>

<p>
  <%= f.submit %>
</p>
<% end %>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited
        this post from being saved:</h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit post</h1>

<%= render 'form' %>

<%= link_to 'Back', action: :index %>

app/views/posts/index.html.erb
<h1>Steve's Tech Blog</h1>
<table class="table table-condensed table-hover">
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td><%= post.text %></td>
      <td><button type="button" class="btn btn_info"><%= link_to 'Show', action: :show, id: post.id %></td>
      <td><button type="button" class="btn btn_info"><%= link_to 'Edit', action: :edit, id: post.id %></td>
      <td><button type="button" class="btn btn_info"><%= link_to 'Destroy', { action: :destroy, id: post.id },
                      method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', action: :index %>

app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @post.text %>
</p>

<h2>Comments</h2>
<%= render @post.comments %>

<h2>Add a comment:</h2>
<%= render "comments/form" %>

<%= link_to 'Edit Post', edit_post_path(@post) %> |
<%= link_to 'Back to Posts', posts_path %>

app/views/welcome/about_me.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>About Me</h1>
    <p>Steve is commonly known and respected by other characters for his kindness to others, his never-ending love and loyalty for those he holds dear, and, alongside with Harriette, his position as a voice of reason and source of wisdom for the often bickering members of the Winslow family, all of which are the redeeming qualities for his generally unwelcome or tolerated presence. He always cares for and means well for other people, but is often the misunderstood victim of the Winslows' anger and rejection, especially of Carl, Eddie and Laura, who all struggle to see through his clumsiness and annoying behavior and to understand and appreciate him for his positive traits.</p>
    <p><a class="btn btn-primary btn-lg">Learn more</a></p>
  </div>
</div>

app/views/welcome/index.html.erb
<div>
  <%= image_tag("SteveUrkel.jpg", class:'img-circle') %>
</div>

<p>
  Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam
  nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat
  volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation
  ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
  Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse
  molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero
  eros et accumsan et iusto odio dignissim qui blandit praesent luptatum
  zzril delenit augue duis dolore te feugait nulla facilisi. Nam liber tempor
  cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim
  placerat facer possim assum. Typi non habent claritatem insitam; est usus leg
  entis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores
  legere me lius quod ii legunt saepius. Claritas est etiam processus dynamicus, qui
</p>

  My Projects: thisiswhyimbroke.com, associatedpress.com, instagram.com

  <div id="carousel-example-generic" class="carousel slide" class=data-interval="25">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
      <li data-target="#carousel-example-generic" data-slide-to="1"></li>
      <li data-target="#carousel-example-generic" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <div class="item active">
        <%= image_tag("associatedpress.png") %>
        <div class="carousel-caption">

        </div>
      </div>
      <div class="item">
        <%= image_tag("instagram.png") %>
        <div class="carousel-caption">

        </div>
      </div>


    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
      <span class="icon-prev"></span>
    </a>
    <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
      <span class="icon-next"></span>
    </a>
  </div>